using Content.Shared.Notifications;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Notifications;

[GenerateTypedNameReferences]
public sealed partial class NotificationEntry : Control
{
    public SharedNotification? Notification { get; set; }

    public NotificationEntry()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Resized()
    {
        base.Resized();
        MessageLabel.SetWidth = Width - MessageLabel.Margin.SumHorizontal;
        MessageLabel.InvalidateArrange();
    }
}

