using Content.Client.UserInterface.Controls;
using Content.Shared.Notifications;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Notifications;

[GenerateTypedNameReferences]
public sealed partial class NotificationsWindow : FancyWindow
{
    public NotificationsWindow()
    {
        RobustXamlLoader.Load(this);
        NotificationContainer.AddChild(new NotificationEntry());
        NotificationContainer.AddChild(new NotificationEntry());
        NotificationContainer.AddChild(new NotificationEntry());
        NotificationContainer.AddChild(new NotificationEntry());
        NotificationContainer.AddChild(new NotificationEntry());
    }

    public void Update(IList<SharedNotification> notifications)
    {
        NotificationContainer.RemoveAllChildren();

        foreach (var notification in notifications)
        {
            var notificationEntry = new NotificationEntry
            {
                Notification = notification,
            };
            NotificationContainer.AddChild(notificationEntry);
        }

    }
}
